name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CI Build"]     # Debe coincidir con 'name: CI Build' del archivo anterior
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: >-
      ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
        || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ot-service-angular
          publish_branch: gh-pages
          force_orphan: true